### ISSUE TITLE
docs: clarify motivations

### ISSUE THREAD

**Issue by getlarge** [push-based/nx-verdaccio-e2e-setup#4]
In the `motivation.md`, I would push even more on the current problems enumeration (with publishable packages e2e tests):
- complex and redundant setup
- can’t be parallelized due to file conflicts (and potential locks from npm/git)
- non-optimized flow, as not cacheable

**Comment by BioPhoton** [comment]
Yes, I will put all 3 mentioned points in the motivation doc and add more details as well as examples.

**Comment by BioPhoton** [comment]
Added more information on:
- can’t be parallelized due to file conflicts (and potential locks from npm/git)
- non-optimized flow, as not cacheable
